apiVersion: v1
kind: Service
metadata:
  name: APP_NAME-litellm-service
  labels:
    app: APP_NAME-litellm
    managed: jac-scale
spec:
  selector:
    app: APP_NAME-litellm
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  type: ClusterIP
